#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Crosschat.Client.Droid.Resource", IsApplication=true)]

namespace Crosschat.Client.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bubble_green = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubble_yellow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int empty_contact = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int image = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int message = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int nick = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int nicknameAndTimeWrapper = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int wrapper = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int image_item_opponent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int image_item_owner = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int message_item_opponent = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int message_item_owner = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
